# Generated by Django 5.1.3 on 2024-11-14 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='thirdname',
            new_name='third_name',
        ),
    ]
