# Generated by Django 5.1.3 on 2024-11-14 15:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_thirdname_customuser_third_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
